import { useState, useEffect } from 'react';

export function AutoDeclarationPanel({ marketId, marketName, openTime, closeTime }) {
  const [autoResults, setAutoResults] = useState(null);
  const [loading, setLoading] = useState(false);
  const [overriding, setOverriding] = useState(false);
  const [showOverride, setShowOverride] = useState(false);
  const [overrideForm, setOverrideForm] = useState({ session: 'open', panel: '' });

  const todayStr = new Date().toISOString().split('T')[0];

  // Fetch auto-declared results
  const fetchAutoResults = async () => {
    setLoading(true);
    try {
      const response = await fetch(`/api/v1/admin/auto-results?marketId=${marketId}&date=${todayStr}`, {
        headers: {
          'Authorization': `Bearer ${localStorage.getItem('matka_admin_token')}`,
          'X-CSRF-Token': import.meta.env.VITE_CSRF_TOKEN || ''
        }
      });

      if (response.ok) {
        const data = await response.json();
        setAutoResults(data.data);
      }
    } catch (error) {
      console.error('Failed to fetch auto results:', error);
    } finally {
      setLoading(false);
    }
  };

  // Override auto-declared result
  const handleOverride = async (e) => {
    e.preventDefault();
    setOverriding(true);

    try {
      const response = await fetch('/api/v1/admin/auto-results/override', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('matka_admin_token')}`,
          'X-CSRF-Token': import.meta.env.VITE_CSRF_TOKEN || ''
        },
        body: JSON.stringify({
          marketId,
          date: todayStr,
          session: overrideForm.session,
          panel: overrideForm.panel
        })
      });

      if (response.ok) {
        fetchAutoResults();
        setShowOverride(false);
        setOverrideForm({ session: 'open', panel: '' });
      } else {
        const error = await response.json();
        alert(`Failed to override: ${error.message}`);
      }
    } catch (error) {
      console.error('Failed to override result:', error);
      alert('Failed to override result');
    } finally {
      setOverriding(false);
    }
  };

  // Generate random panel for preview
  const generateRandomPanel = async () => {
    try {
      const response = await fetch('/api/v1/admin/generate-panel', {
        headers: {
          'Authorization': `Bearer ${localStorage.getItem('matka_admin_token')}`,
          'X-CSRF-Token': import.meta.env.VITE_CSRF_TOKEN || ''
        }
      });

      if (response.ok) {
        const data = await response.json();
        setOverrideForm(prev => ({ ...prev, panel: data.data.panel }));
      }
    } catch (error) {
      console.error('Failed to generate random panel:', error);
    }
  };

  // Trigger auto-declaration check
  const triggerAutoCheck = async () => {
    try {
      const response = await fetch('/api/v1/admin/auto-results/trigger', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${localStorage.getItem('matka_admin_token')}`,
          'X-CSRF-Token': import.meta.env.VITE_CSRF_TOKEN || ''
        }
      });

      if (response.ok) {
        fetchAutoResults();
      }
    } catch (error) {
      console.error('Failed to trigger auto check:', error);
    }
  };

  useEffect(() => {
    fetchAutoResults();
    
    // Refresh every 30 seconds
    const interval = setInterval(fetchAutoResults, 30000);
    return () => clearInterval(interval);
  }, [marketId]);

  if (loading && !autoResults) {
    return (
      <div className="auto-declaration-loading">
        <div className="auto-spinner"></div>
        <span>Loading auto-declaration status...</span>
      </div>
    );
  }

  const hasAutoResults = autoResults?.openPanel || autoResults?.closePanel;

  return (
    <div className="auto-declaration-container">
      <div className="auto-declaration-header">
        <div className="auto-declaration-info">
          <div className="auto-icon">🤖</div>
          <div>
            <h4>Auto Declaration - {marketName}</h4>
            <p>System automatically generates results 1 minute before time</p>
          </div>
        </div>
        <div className="auto-actions">
          <button
            onClick={triggerAutoCheck}
            className="auto-btn auto-btn-secondary"
          >
            Check Now
          </button>
          <button
            onClick={() => setShowOverride(!showOverride)}
            className="auto-btn auto-btn-primary"
          >
            Override
          </button>
        </div>
      </div>

      <div className="auto-results-grid">
        <div className="auto-result-card">
          <div className="auto-result-header">
            <span className="auto-time">Open Time: {openTime}</span>
            {autoResults?.isAutoGenerated?.open && (
              <span className="auto-badge">AUTO</span>
            )}
          </div>
          <div className="auto-result-value">
            {autoResults?.openPanel || '---'}
          </div>
        </div>

        <div className="auto-result-card">
          <div className="auto-result-header">
            <span className="auto-time">Close Time: {closeTime}</span>
            {autoResults?.isAutoGenerated?.close && (
              <span className="auto-badge">AUTO</span>
            )}
          </div>
          <div className="auto-result-value">
            {autoResults?.closePanel || '---'}
          </div>
        </div>
      </div>

      {autoResults?.jodi && (
        <div className="auto-jodi-display">
          <div className="auto-jodi-badge">
            <span>Jodi: </span>
            <strong>{autoResults.jodi}</strong>
          </div>
        </div>
      )}

      {hasAutoResults && (
        <div className="auto-status-info">
          <div className="auto-status-icon">✅</div>
          <span>
            Auto-declaration active. System will automatically declare results 1 minute before time if not manually set.
          </span>
        </div>
      )}

      {showOverride && (
        <div className="auto-override-panel">
          <h4>Override Auto-Declared Result</h4>
          <form onSubmit={handleOverride} className="auto-override-form">
            <div className="auto-form-row">
              <label>Session</label>
              <select
                value={overrideForm.session}
                onChange={(e) => setOverrideForm(prev => ({ ...prev, session: e.target.value }))}
              >
                <option value="open">Open</option>
                <option value="close">Close</option>
              </select>
            </div>

            <div className="auto-form-row">
              <label>Panel (3 digits)</label>
              <div className="auto-panel-input">
                <input
                  type="text"
                  value={overrideForm.panel}
                  onChange={(e) => setOverrideForm(prev => ({ ...prev, panel: e.target.value.slice(0, 3) }))}
                  placeholder="000"
                  pattern="[0-9]{3}"
                  maxLength={3}
                  required
                />
                <button
                  type="button"
                  onClick={generateRandomPanel}
                  className="auto-btn auto-btn-small"
                >
                  Random
                </button>
              </div>
            </div>

            <div className="auto-form-actions">
              <button
                type="submit"
                disabled={overriding}
                className="auto-btn auto-btn-primary auto-btn-full"
              >
                {overriding ? 'Overriding...' : 'Override Result'}
              </button>
              <button
                type="button"
                onClick={() => setShowOverride(false)}
                className="auto-btn auto-btn-secondary"
              >
                Cancel
              </button>
            </div>
          </form>
        </div>
      )}

      <div className="auto-help-text">
        <div>• System automatically generates results 1 minute before declaration time</div>
        <div>• Auto-generated results are marked with "AUTO" badge</div>
        <div>• Admin can override auto-generated results at any time</div>
        <div>• Manual results take priority over auto-generated ones</div>
      </div>

      <style jsx>{`
        .auto-declaration-container {
          background: linear-gradient(135deg, #f8faff 0%, #f0f4ff 100%);
          border: 1px solid #e2e8f0;
          border-radius: 12px;
          padding: 20px;
          margin-top: 16px;
        }

        .auto-declaration-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 20px;
        }

        .auto-declaration-info {
          display: flex;
          align-items: center;
          gap: 12px;
        }

        .auto-icon {
          font-size: 24px;
          width: 40px;
          height: 40px;
          display: flex;
          align-items: center;
          justify-content: center;
          background: #3b82f6;
          border-radius: 8px;
        }

        .auto-declaration-info h4 {
          margin: 0;
          font-size: 16px;
          font-weight: 600;
          color: #1e293b;
        }

        .auto-declaration-info p {
          margin: 4px 0 0 0;
          font-size: 14px;
          color: #64748b;
        }

        .auto-actions {
          display: flex;
          gap: 8px;
        }

        .auto-btn {
          padding: 8px 16px;
          border-radius: 6px;
          border: none;
          font-size: 14px;
          font-weight: 500;
          cursor: pointer;
          transition: all 0.2s;
        }

        .auto-btn-primary {
          background: #3b82f6;
          color: white;
        }

        .auto-btn-primary:hover {
          background: #2563eb;
        }

        .auto-btn-secondary {
          background: #f1f5f9;
          color: #475569;
          border: 1px solid #e2e8f0;
        }

        .auto-btn-secondary:hover {
          background: #e2e8f0;
        }

        .auto-btn-small {
          padding: 6px 12px;
          font-size: 12px;
        }

        .auto-btn-full {
          width: 100%;
        }

        .auto-results-grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 16px;
          margin-bottom: 16px;
        }

        .auto-result-card {
          background: white;
          border: 1px solid #e2e8f0;
          border-radius: 8px;
          padding: 16px;
        }

        .auto-result-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 12px;
        }

        .auto-time {
          font-size: 14px;
          font-weight: 500;
          color: #475569;
        }

        .auto-badge {
          background: #10b981;
          color: white;
          font-size: 11px;
          font-weight: 600;
          padding: 2px 6px;
          border-radius: 4px;
        }

        .auto-result-value {
          font-size: 24px;
          font-weight: 700;
          text-align: center;
          padding: 12px;
          background: #f8fafc;
          border-radius: 6px;
          color: #1e293b;
        }

        .auto-jodi-display {
          text-align: center;
          margin-bottom: 16px;
        }

        .auto-jodi-badge {
          display: inline-block;
          background: linear-gradient(135deg, #3b82f6 0%, #8b5cf6 100%);
          color: white;
          padding: 8px 16px;
          border-radius: 20px;
          font-size: 16px;
          font-weight: 600;
        }

        .auto-status-info {
          display: flex;
          align-items: center;
          gap: 8px;
          background: #dcfce7;
          border: 1px solid #bbf7d0;
          border-radius: 8px;
          padding: 12px;
          margin-bottom: 16px;
          font-size: 14px;
          color: #166534;
        }

        .auto-status-icon {
          font-size: 16px;
        }

        .auto-override-panel {
          background: white;
          border: 1px solid #e2e8f0;
          border-radius: 8px;
          padding: 16px;
          margin-bottom: 16px;
        }

        .auto-override-panel h4 {
          margin: 0 0 16px 0;
          font-size: 16px;
          color: #1e293b;
        }

        .auto-form-row {
          margin-bottom: 12px;
        }

        .auto-form-row label {
          display: block;
          margin-bottom: 4px;
          font-size: 14px;
          font-weight: 500;
          color: #374151;
        }

        .auto-form-row select,
        .auto-form-row input {
          width: 100%;
          padding: 8px 12px;
          border: 1px solid #d1d5db;
          border-radius: 6px;
          font-size: 14px;
        }

        .auto-panel-input {
          display: flex;
          gap: 8px;
        }

        .auto-panel-input input {
          flex: 1;
          text-align: center;
          font-family: monospace;
          font-size: 18px;
          font-weight: 600;
        }

        .auto-form-actions {
          display: flex;
          gap: 8px;
          margin-top: 16px;
        }

        .auto-help-text {
          font-size: 12px;
          color: #64748b;
          line-height: 1.4;
        }

        .auto-help-text div {
          margin-bottom: 2px;
        }

        .auto-declaration-loading {
          display: flex;
          align-items: center;
          gap: 8px;
          padding: 20px;
          background: #f8fafc;
          border-radius: 8px;
          font-size: 14px;
          color: #64748b;
        }

        .auto-spinner {
          width: 16px;
          height: 16px;
          border: 2px solid #e2e8f0;
          border-top: 2px solid #3b82f6;
          border-radius: 50%;
          animation: spin 1s linear infinite;
        }

        @keyframes spin {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
        }

        @media (max-width: 768px) {
          .auto-results-grid {
            grid-template-columns: 1fr;
          }
          
          .auto-declaration-header {
            flex-direction: column;
            align-items: flex-start;
            gap: 12px;
          }
          
          .auto-actions {
            width: 100%;
            justify-content: flex-end;
          }
        }
      `}</style>
    </div>
  );
}